apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ required "name must be set" .Values.persistentVolume.name }}
  annotations:
    "helm.sh/resource-policy": "keep"
spec:
  capacity:
    storage: {{ required "size must be set" .Values.persistentVolume.size }}
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.reclaimPolicy }}
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath }}/{{ required "hostSubPath must be set" .Values.persistentVolume.hostSubPath }}
