---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb2-auth
  namespace: influxdb
spec:
  encryptedData:
    admin-password: AgDBy5b6g8qwRTdAikFMhVNcCf9H4n1+KOdeRspejG7hgz1yAIArluZb6uR5Zl+hM1Cfo4YdtJqpeZLK5GC+HkBy90q/FURa34HkjnH2u7Izk2udQ0G6gRXrtho5B8NT4MAL2dHxnTtGHqDlryr5HPuk74ZSgCXRrZU85ZI34Uyk5gWLBFEspIduaSdB3WhNtSOkQxwbZgZDDYEF1IrW9U5VD0zrSIcYPO3BFrwJyXIa8O8f8a6hGjm1sKUEhU0UTPGJekyr89uskOmlmSzzUP/30MhVnvnmoElpggmJBGmg000Vlmj3o/Qv5b4OzI8NtGhi/5Sw0QAVeRlNNrrD0mDxjtwUkxrM6n+/KU2KSwX+kAu+CleeachM+KyV9b8qGp9coND18blKPAczrNhIv/Pex8fzHxmT8Tr7V8MkH63CQqtZ7BcAG3RZzWOw191z4g1vwiQMk7HRhxAoQMMvB6oqxqyf3lka/nMI7776YWRJyqGEyxdcOZ2C5rszaffYrNoG/fOBbSSgiMN0bwWuA0Uvdbzm8K4VCwtVXsAQxMZs5Huq4Ws5NpYnsi8w4Yg492OX2iFEqDILYoaIe96Ml+qXZl7BpOkGZ7HxYBiW3rW34HoxXKpfiX2uvKdrrpdVAZjOrMtAPnKjXidepalAdQwJSDMv0ydH19Vaw3715RcDMSSapDWmxSWTiUZAl8eJp/ldoN37rzgijE/K1eWW67s+wWKomOSeSikc1B21yIdsUw==
    admin-token: AgClZgshr73D+0S2q7Uewzvc9TwF3nRuCjAyzs621l0oebHkRaxpOcO7GxVSFSRGZnrmalESM2oghDIWLr2qHw8AxQPHqS4YTG74PtbpCVBedziRJSR09dCVz5F7Xo4i/Jbejn+uUuDY57567Q4+gWvgun1bJQfRMwLnF6j/VpmwLzs+RTMsPXYab0fCRPhfqNhJfd0klXvjxZINz8p0PARTfULzU1pixGJ+epcFaVJYlDEdA+QmgDZQE/B4g4P4EMkpjRAnA7BaXSW531KkBthiFZU7uGfwh13pZZI9jJmsoY77sPSjd4ppbHUdW65uVHgc9duvENkFpiHO+OC3hXTLB8AgXNs5BTuuVJJTXxKQyNOWaqs9CWp+9nqa4osjaSbTV3+D0S4/7aAkh+yrZr8oF6pburRTdqTgfFWPgh9QI9S9PLk+vemgyX6gRiBpFWMnEJ3MfiTjZ/GXmFJNaBJAK1U/4qDyNQtU5gUyeU24tBPriJdDYkehKMYHBXs06P/Drub4lFTR3FwCLd7Dwo8nx1DqaSKl8getGKUmCKJEcw62SfujmcLHAq1C2t5xVGgHsXUB3MlvFZ4zc0ywKVrxqw/vik9oCldgDnVX4RghRpuR3w3qo4HWZgV9wB1xRtmIyjpkIj6Sp/gEXdQVvOHQOvoAj64yWkgwUzROtO5zhFcomOFyVAP/QPk6m1X3eWkuwRdzqpj5AqE205deHg7jB4v3CfFi9UY/jM4rR27JnA==
  template:
    metadata:
      annotations:
        helm.sh/resource-policy: keep
        meta.helm.sh/release-name: influxdb2
        meta.helm.sh/release-namespace: influxdb
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: influxdb2
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: influxdb2
        app.kubernetes.io/version: 2.7.4
        helm.sh/chart: influxdb2-2.1.2
      name: influxdb2-auth
      namespace: influxdb
    type: Opaque
